sudo: required
dist: trusty
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: ndOkRjO2FHp6gmwJVu54l5mUGKJxDlvjC1EQBiuIUydaGhFUQmo7o+ui2Ohq2W73Uw1AJvVGgllGwfcUtbBr7r23UfcZX5CafwRW1CrkW5h4lKp4vFEOkxGTXCoqNTGwkBrl6RgBw7NudUsG5I5EL5c+6yA3EqP0uG0HPzIBwc4sNWH1PJY6268hasOQBHhdMplsyZBn/mIbXyuloIQK6Qvdv7Koi77nqfHGEscboN67y3oOWBSf9gE5r55kq4OHyOMyCs7xMw683Fs4CAk2XOYwXQLxhNTdDL4xdKPji2TUG4PZ795agioN8EtQUH6rNacDdcZUlg4uztcO4kempAIfKW0dfjFwNN/puA7T3cNxufC77W7MGBsKb4UFjf7zhRwM/LbJgv4LP1bhJqk16gEgCf/ilfgZXcqbCA2dKi6bGXGWCKsh+o0pi//cnRVbvqQWCtTS5gYVXgH0MNUIxiTljQ1oAJpXDtOGl9yS6C1XreL5T4UO35Ih7SJqcW+mhB0b55MVimVgpzu2d8t2MHeHXEVXXBxnSkVVS8wuwUxok3x9fbu0MzoazAwjdEc8mB4VjkGkeVjJelQzT7yDz6FbbUFLle2s7dSdSSdrfwOMgodbAXZFEcC9Lc4LgLXc31hCnbElNxtSHM/Is82pri9U6j7noeS7NLqMHFSAVYM=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: a7mw09AHTVTJYqdA+S6U7/Lazf6PDQRNxziqEqOS4xUxddYbCEdZuZ+tVVLods5scG8njmT431mLR9A9buBf7WWvXsvVJniU46eg1CpqTagRknR6Z7hr4IvSse2p5ZKs3ASaF2Sv76IJq/nvs7/QGfyzzOP5p7trZ4ll39df/kXNrfVQmF5ZOf6yF4mSJxsnbnEBR+vBrgLyEne98yDzh8f1VhlYR7Y0KOqbUqbgTy0VIFoM9gtRz7N6q+ITnCMKyde47HZy4/E65/IhWzJj0LyIPgiV/UA7sHx9+g5a3GSFTAYfZVr6lJzZqRaUKiAQ+B2SAKVr+l1wjhi2Ip68HTrb6nT4EELnnAIl8hszoFtvSYvi6/1ZkDBSRD5RLRLJ27POKCZNbvmVjUmzvkw+2L7KloygHsy7W++H1jSB4ySQ1DpvLcpSbNb2AVyqOl/KjSIoDIsDdJiG0lvcqOb5jvSpKH2ys7p2hiYqZ2U7lXyLeNQJHEYfL1sj4R8TQEzhG8H/X3D2FkAj/JGewbdTMj/GlnXnqMwoMTCScNkV4XLHuwq5suCFTFfnODJORx8F/JNV/kZDXsT3iFhrJxl5rgSa0YN3GA94CPAwlajSgsxLIUhE92KEOP7esDaLQG5LZQEUoBSPHj9oc59S9uwVsA3pm9Rc9V1J3Do7ombnygE=
